#!/usr/bin/env ruby


def importsubnet(sub)
	ips =  %x(cat ../../allcomps2 | grep "#{sub}" | while read line; do echo $line; done)
	puts "#{ips}"
    		ip=ips.split("|")
	  	i=1
		begin
	#	 puts "1 #{ip[0+i]}"
	#	 puts "2 #{ip[1+i]}"
	#	 puts "3 #{ip[2+i]}"
	#	 puts "4 #{ip[3+i]}"
	#	 puts "5 #{ip[4+i]}"
	#	 puts "6 #{ip[5+i]}"
	#	 puts "7 #{ip[6+i]}"
	#	 puts "8 #{ip[7+i]}"
		 puts "mac:  #{ip[1+i]} ip: #{ip[2+i]} hostname: #{ip[3+i]} tftp: #{ip[4+i]} discr:  #{ip[5+i]}"
                 @newhost = Subnet.find_by_adress("192.168.177.0").hosts.new(:hostname => ip[3+i], :ip => ip[2+i], :mac => ip[1+i], :discription => ip[5+i], :tftp_id => Tftp.find_by_image(ip[4+i]).id)

#ip: nil, mac: nil, discription: nil, tftp_id: nil, subnet_id: 2, created_at: nil, updated_at: nil, lastping: nil
                  
		 i+=7
		end while i < ip.length


end

importsubnet("192.168.177")
